name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@master
      - name: Build the Docker container image
        run: docker build ./ -f ./Dockerfile -t marley/jsdev.org:latest
